title:        {"Containers"}
url:          http://federal-agency-dataset-adoption.publicprivatesector.org/
version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true

permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 50
paginate_path: "/news/page:num"

production_url : http://federal-agency-dataset-adoption.publicprivatesector.org/

BASE_PATH : http://federal-agency-dataset-adoption.publicprivatesector.org/

categories_path : /categories.html
tags_path : /tags.html
